version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/apps/nextjs"
    schedule:
      interval: "weekly"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/apps/agents"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
